### ISSUE TITLE
Does hiberlite handle inheritance?

### ISSUE THREAD

**Issue by wtholliday** [paulftw/hiberlite#13]
In my case I have a bunch of classes which inherit from a common base. Can hiberlite handle this? Specifically, can I do the following?

```
HIBERLITE_EXPORT_CLASS(Base);
HIBERLITE_EXPORT_CLASS(Derived);
```

and then would `db.getAllBeans<Base>();` return all instances of Derived as well?

Thanks!

**Comment by pbianchi** [comment]
That information would be of a great help for me too. Thanks in advance.

Pedro

**Comment by d-led** [comment]
If I understand the Idea correctly, then inheritance is rather discouraged in ORM, as it is strictly not necessary. It can be argued that separating logic from data is good for maintainability. When building simple [DTO](http://en.wikipedia.org/wiki/Data_transfer_object)s, inheritance maps onto composition well. Based on that, you can then create polymorphic instances by dispatching according to the DTOs that you get from queries.

It is very easy to use composition, for which hiberlite works well.

**Comment by wtholliday** [comment]
Ok, cool. How exactly would I represent, say, a collection of objects which all (formerly) derive from a base class?

**Comment by d-led** [comment]
here's a test for you to show the concept of what I mean: [gist](https://gist.github.com/d-led/1f6b8d27fd8e66d4fcb0)

**Comment by d-led** [comment]
proposing to close

**Comment by d-led** [comment]
@wtholliday : http://en.wikipedia.org/wiki/Object-relational_impedance_mismatch#Interface.2C_class.2C_inheritance_and_polymorphism

**Comment by wtholliday** [comment]
Thanks @d-led. Very informative!
