### ISSUE TITLE
Biicode integration

### ISSUE THREAD

**Issue by rharriso** [paulftw/hiberlite#15]
Is anyone else interested in making this compatible with biicode. I've got an initial version of the block working on my fork: https://github.com/rharriso/hiberlite

Travis integration doesn't seem to be cooperating.

**Comment by d-led** [comment]
```
ERROR: You're not in a valid project folder
The command "bii test" exited with 1.
```

I'm not familiar with bii, but the next step would be to correct that. Is there a non-intrusive way to provide a bii config, as in without moving the source? Another option would be a submodule

**Comment by rharriso** [comment]
I've gotten the tests to pass locally, just not with travis. I'm just trying to judge interest. I'm not going to prioritize this if others aren't interested. I've already got it working in my own projects.

**Comment by d-led** [comment]
I propose to close then until further interest arises

**Comment by rharriso** [comment]
Ok, sounds fine to me.
