### ISSUE TITLE
decltype problem

### ISSUE THREAD

**Issue by rbarreiros** [paulftw/hiberlite#7]
Got this error with gcc 4.7.3 and gcc 4.6.3

sample.cpp:13:8: error: ‘Person::name’ cannot appear in a constant-expression
sample.cpp:13:8: error: a function call cannot appear in a constant-expression
sample.cpp:13:8: error: template argument 1 is invalid

The problem is in HIBERLITE_NVP macro on decltype, if I change to macro from 
# define HIBERLITE_NVP(Field) hiberlite::sql_nvp< decltype(Field) >(#Field,Field)

to
# define HIBERLITE_NVP(Type, Field) hiberlite::sql_nvp< Type >(#Field,Field)

works as a short term solution, I have no idea on how to fix this in order to keep the original implementation.

Best regards.

**Comment by minorsecond** [comment]
[I think this issue may be occuring again](http://pastebin.com/zKge4MBE). Tried compiling sample.cpp and am getting similar issues to the original poster above.

**Comment by d-led** [comment]
`$ g++ -Ofast -o sample sample.cpp`
->
`$ g++ -std=c++0x -Ofast -o sample sample.cpp` ?

btw, which OS?

**Comment by minorsecond** [comment]
Both commands produce the same result.

I'm on Gentoo Linux.

**Comment by d-led** [comment]
I think, it's nearly impossible to follow up, since there can be too many issues: where the headers lie, is it a fresh build, or an update from an earlier commit, etc, etc. I've just tried it out (+ the travis-ci build passes), hence you might want to try building everything from scratch from the latest commit, and perhaps regenerate the makefiles using premake

**Comment by minorsecond** [comment]
Are you on Linux? I can test from another distro if that would be easier
for you. As I'm on BTRFS it'll be easy to just create a new subvolume.
Maybe Debian?

**Comment by d-led** [comment]
Let's try the following: make a travis-ci-only repo (like [*this one](https://github.com/d-led/csharp_travis_example)) on github, which will simply contain exactly that: check out of hiberlite, `make && sudo make install` and then your desired build step. This will be a self-contained example that we'll try to analyze
